[package]
name = "rust-webgl"
version = "0.1.0"
authors = ["Riku Sugawara"]
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"
repository = "https://github.com/reeq20/rust-webgl"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"